name: Testing golang out

on:
  workflow_dispatch:

permissions:
  contents: read
  pages: write
  id-token: write

jobs:
  build:
    name: Build
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - name: Golang setup
        uses: actions/setup-go@v4
        with:
          go-version: stable
          check-latest: true

      - name: make questions
        env:
          TEST-ENV: ${{secrets.TEST_ENV}}
          A1: ${{secrets.A1}}
        working-directory: ./src/testgo
        run: go run .
